In [1]:
begin
    using Pkg
    dev_folder = joinpath(@__DIR__, "../Examples")
    Pkg.activate(dev_folder)
end
Threads.nthreads()

  Activating project at `~/Realizibility_index/BindingAndCatalysis.jl/Examples`


24

In [3]:
using Polyhedra
using GLMakie # for plotting, we use Makie backend, could also be GLMakie or WGLMakie...
using Revise
using BindingAndCatalysis # import the package

[ Info: Precompiling BindingAndCatalysis [b532a4b1-2c45-4c12-bcaf-8695372aa40c] (cache misses: include_dependency fsize change (2), wrong dep version loaded (2), incompatible header (4))


A TF dimerize and then binds with a promoter the complex can trigger the production of a protein, and the degradation of the protein can happened in all forms, complex, monomer and dimer, but we know the degradation on complex have to be slower than the degradation of monomer and dimer,  so we can treat the degradation happens only on monomer and dimer.

In [4]:
model = let 
    x = [:D, :P, :P₂, :C]
    q = [:tP, :tD]
    N = [0 2 -1 0
        1 0 1 -1]
    Bnc(N=N, x_sym=x, q_sym=q)
end

let
    Γ = [1 -1 -1]
    Π = [1 0 0
        0 1 0
        0 0 1]
    k_sym = [:k₁, :k₂, :k₃]
    q_picked=[:tP]
    x_picked=[:C, :P, :P₂]
    update_catalysis!(model;Γ=Γ, Π=Π, k_sym=k_sym, x_picked=x_picked, q_picked=q_picked)
end


[ Info: q is reordered to make catalysis-involving species first


In [32]:
show_conservation(model)

2-element Vector{Symbolics.Equation}:
 tP ~ C + D
 tD ~ 2C + P + 2P₂

In [5]:
find_all_regimes!(model)

[ Info: ---------------------Start finding all vertices--------------------
[ Info: Finished, with 6 vertices found and 6 asymptotic vertices.
[ Info: 2.Calculating nullity for each vertex...
[ Info: 3.Building Regimes...
[ Info: Finished.


In [6]:
find_catalysis_regimes!(model)

[ Info: ---------------------Start finding all vertices--------------------
[ Info: Finished, with 2 catalysis vertices found and 2 asymptotic vertices.
[ Info: 3.Building Regimes...


In [12]:
match_regimes!(model)

[ Info: Matching Catalysis Regimes and Binding Regimes to build BncRegimes...
[ Info: Finished matching BncRegimes.
[ Info: Initializing BncRegimes, calculating H, H0, C_qKk_ss, C0_qKk_ss, C_qKk_cat, C0_qKk_cat for each regime...


LoadError: TaskFailedException

    nested task error: DimensionMismatch: mismatch in dimension 1 (expected 4 got 1)
    Stacktrace:
      [1] _cs
        @ ./abstractarray.jl:1839 [inlined]
      [2] _cshp
        @ ./abstractarray.jl:1835 [inlined]
      [3] _cat_size_shape
        @ ./abstractarray.jl:1815 [inlined]
      [4] cat_size_shape
        @ ./abstractarray.jl:1813 [inlined]
      [5] _cat_t
        @ ./abstractarray.jl:1854 [inlined]
      [6] typed_hcat(::Type{Float64}, ::SparseArrays.SparseMatrixCSC{Float64, Int64}, ::Int64)
        @ Base ./abstractarray.jl:2001
      [7] hcat(X1::SparseArrays.SparseMatrixCSC{Float64, Int64}, X::Int64)
        @ SparseArrays ~/.julia/juliaup/julia-1.12.5+0.x64.linux.gnu/share/julia/stdlib/v1.12/SparseArrays/src/sparsevector.jl:1273
      [8] _calc_C_qKk_cat(bind_rgm::BindingAndCatalysis.BindRegime{Float64, Int64}, cat_rgm::BindingAndCatalysis.CatalysisRegime)
        @ BindingAndCatalysis ~/Realizibility_index/BindingAndCatalysis.jl/src/Catalysis_regime.jl:309
      [9] macro expansion
        @ ~/Realizibility_index/BindingAndCatalysis.jl/src/Catalysis_regime.jl:185 [inlined]
     [10] (::BindingAndCatalysis.var"#_initialize_regime!##46#_initialize_regime!##47"{…})(tid::Int64; onethread::Bool)
        @ BindingAndCatalysis ~/Realizibility_index/BindingAndCatalysis.jl/src/Catalysis_regime.jl:186
     [11] #_initialize_regime!##46
        @ ./threadingconstructs.jl:243 [inlined]
     [12] (::Base.Threads.var"#threading_run##0#threading_run##1"{…})()
        @ Base.Threads ./threadingconstructs.jl:177

...and 5 more exceptions.


In [8]:
model.BncRegimes

2×6 Matrix{Union{Nothing, BindingAndCatalysis.BncRegime}}:
 BncRegime(BindRegime{Float64, Int64}(Bnc{Int64}(sparse([2, 1, 1, 2, 2], [1, 2, 3, 3, 4], [1, 2, -1, 1, -1], 2, 4), sparse([1, 2, 2, 1, 2], [1, 2, 3, 4, 4], [1, 1, 2, 1, 2], 2, 4), 2, 4, 2, Num[D, P, P₂, C], Num[tP, tD], Num[K₁, K₂], CatalysisData(Bnc{Int64}(#= circular reference @-2 =#), sparse([1, 1, 1], [1, 2, 3], [1, -1, -1], 1, 3), sparse([2, 3, 1], [2, 3, 4], [1, 1, 1], 3, 4), sparse([1, 1, 1], [1, 2, 3], [1, -1, -1], 1, 3), sparse(Int64[], Int64[], Int64[], 1, 0), 1, 3, 1, 1, Num[k₁, k₂, k₃], sparse([1, 1, 1], [1, 2, 3], [1.0, -1.0, -1.0], 1, 3), sparse([2, 3, 1], [2, 3, 4], [1.0, 1.0, 1.0], 3, 4), sparse([1, 2, 2], [1, 2, 3], [1, 1, 1], 2, 3), MatrixHelper{Int64}(3, [[1], [2, 3]], [[1, 0, 0], [0, 1, 2]], [[0.0], [0.0, 0.0]], [1, 1, 2], 1, Vector{Vector{ChoiceIneq}}[[[]], [[ChoiceIneq(1, 1, 3, 0.0)], [ChoiceIneq(1, -1, 2, 0.0)]]], Hyperplane_perm{Int64}[Hyperplane_perm{Int64}(2, 3, 1, 1, 0.0, sparsevec([2, 3], Int8[1, -1

In [10]:
typeof(model.catalysis.CatalysisRegimes)

BindingAndCatalysis.Regimes{Int64, BindingAndCatalysis.CatalysisRegime, Vector{BindingAndCatalysis.CatalysisRegime}}

In [10]:
model.catalysis.r_v

1

In [11]:
P* pi *H

1-element Vector{Int64}:
 -1

In [12]:
model = let 
    L = [0 1 1; 1 0 1]
    N = [1 1 -1]
    Bnc(L=L,N=N)
end

----------Binding Network Summary:-------------
Number of species (n): 3
Number of conserved quantities (d): 2
Number of reactions (r): 1
L matrix: [0 1 1; 1 0 1]
N matrix: [1 1 -1]
Direction of binding reactions: forward
Catalysis involved: No
Regimes constructed: No
-----------------------------------------------

In [19]:
get_H(model,2)

3×3 SparseMatrixCSC{Float64, Int64} with 5 stored entries:
 -1.0  1.0  1.0
  1.0   ⋅    ⋅ 
   ⋅   1.0   ⋅ 

In [23]:
M1= get_M(model,2)

3×3 SparseMatrixCSC{Int64, Int64} with 5 stored entries:
 ⋅  1   ⋅
 ⋅  ⋅   1
 1  1  -1

In [24]:
M2 = get_M(model,4)

3×3 SparseMatrixCSC{Int64, Int64} with 5 stored entries:
 ⋅  ⋅   1
 ⋅  ⋅   1
 1  1  -1

In [22]:
a = inv([0 0 1 ;1 1 -1;0 -1 1])

3×3 Matrix{Float64}:
 -0.0  1.0   1.0
  1.0  0.0  -1.0
  1.0  0.0   0.0

In [25]:
M1 *a

3×3 Matrix{Float64}:
 1.0  0.0  -1.0
 1.0  0.0   0.0
 0.0  1.0   0.0

In [26]:
M2 *a

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 1.0  0.0  0.0
 0.0  1.0  0.0

In [ ]:
function S_to_S_pos_neg(S::Matrix)
    S_p = zeros(size(S))
    S_n = zeros(size(S))
    for i in eachindex(S)
        if S[i] > 0
            S_p[i] = S[i]
        elseif S[i] < 0
            S_n[i] = -S[i]
        end
    end
    return S_p, S_n
end
    