In [94]:
begin
    using Pkg
    dev_folder = joinpath(@__DIR__, "../Examples")
    Pkg.activate(dev_folder)
end
Threads.nthreads()

  Activating project at `~/Realizibility_index/BindingAndCatalysis.jl/Examples`


24

In [2]:
using Polyhedra
using GLMakie # for plotting, we use Makie backend, could also be GLMakie or WGLMakie...
using Revise
using BindingAndCatalysis # import the package

[ Info: Precompiling BindingAndCatalysis [b532a4b1-2c45-4c12-bcaf-8695372aa40c] (cache misses: include_dependency fsize change (2), incompatible header (4))

SYSTEM: caught exception of type :MethodError while trying to print a failed Task notice; giving up

SYSTEM: caught exception of type :MethodError while trying to print a failed Task notice; giving up

SYSTEM: caught exception of type :MethodError while trying to print a failed Task notice; giving up

SYSTEM: caught exception of type :MethodError while trying to print a failed Task notice; giving up

SYSTEM: caught exception of type :MethodError while trying to print a failed Task notice; giving up

SYSTEM: caught exception of type :MethodError while trying to print a failed Task notice; giving up

SYSTEM: caught exception of type :MethodError while trying to print a failed Task notice; giving up

SYSTEM: caught exception of type :MethodError while trying to print a failed Task notice; giving up

SYSTEM: caught exception of type :

In [64]:
model = let
    N = N_generator(4,8)
    Bnc(N=N)
end


----------Binding Network Summary:-------------
Number of species (n): 8
Number of conserved quantities (d): 4
Number of reactions (r): 4
L matrix: [1 0 … 1 0; 0 1 … 1 1; 0 0 … 0 1; 0 0 … 0 1]
N matrix: [0 1 … 0 0; 1 1 … 0 0; 1 1 … -1 0; 0 0 … 0 -1]
Direction of binding reactions: forward
Catalysis involved: No
Regimes constructed: No
-----------------------------------------------

In [66]:
model.L

4×8 Matrix{Int64}:
 1  0  0  0  0  1  1  0
 0  1  0  0  1  1  1  1
 0  0  1  0  0  0  0  1
 0  0  0  1  1  0  0  1

In [67]:
f(i)= let
    C,C0,nulliy = get_C_C0_nullity(model,i)
    get_polyhedron(hcat(C0,C), zeros(size(C0)), nulliy)
end

f (generic function with 1 method)

In [68]:
g(i) = let
    C,C0 = get_C_C0_x(model,i)
    get_polyhedron(hcat(C0,C), zeros(size(C0)))
end

g (generic function with 1 method)

In [69]:
vrep(g(1))

[ Info: ---------------------Start finding all vertices--------------------
[ Info: Finished, with 66 vertices found and 66 asymptotic vertices.
[ Info: -------------Start calculating nullity for each vertex, it also takes a while.------------
[ Info: 1.Building Nρ_inv cache in parallel...
[ Info: 2.Calculating nullity for each vertex in parallel...


V-representation CDDLib.CDDGeneratorMatrix{Float64, Float64}:
1-element iterator of Vector{Float64}:
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
2-element iterator of Line{Float64, Vector{Float64}}:
 Line([1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
 Line([0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]),
9-element iterator of Ray{Float64, Vector{Float64}}:
 Ray([0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -1.0, 0.0])
 Ray([0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
 Ray([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0])
 Ray([0.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1.0, -1.0, 0.0])
 Ray([0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0])
 Ray([0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0])
 Ray([0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0])
 Ray([0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0])
 Ray([0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0])

In [70]:
vrep(g(2))

V-representation CDDLib.CDDGeneratorMatrix{Float64, Float64}:
1-element iterator of Vector{Float64}:
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
2-element iterator of Line{Float64, Vector{Float64}}:
 Line([1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
 Line([0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]),
9-element iterator of Ray{Float64, Vector{Float64}}:
 Ray([0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -1.0, 0.0])
 Ray([0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
 Ray([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0])
 Ray([0.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1.0, -1.0, 0.0])
 Ray([0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0])
 Ray([0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0])
 Ray([0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0])
 Ray([0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0])
 Ray([0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0])

In [55]:
vrep(f(1))

[ Info: ---------------------Start finding all vertices--------------------
[ Info: Finished, with 4 vertices found and 4 asymptotic vertices.
[ Info: -------------Start calculating nullity for each vertex, it also takes a while.------------
[ Info: 1.Building Nρ_inv cache in parallel...
[ Info: 2.Calculating nullity for each vertex in parallel...


V-representation CDDLib.CDDGeneratorMatrix{Float64, Float64}:
1-element iterator of Vector{Float64}:
 [0.0, 0.0, 0.0, 0.0],
2-element iterator of Line{Float64, Vector{Float64}}:
 Line([1.0, 0.0, 0.0, 0.0])
 Line([0.0, 1.0, 1.0, 1.0]),
2-element iterator of Ray{Float64, Vector{Float64}}:
 Ray([0.0, -1.0, 0.0, 0.0])
 Ray([0.0, -0.0, -1.0, 0.0])

In [56]:
vrep(f(2))

V-representation CDDLib.CDDGeneratorMatrix{Float64, Float64}:
1-element iterator of Vector{Float64}:
 [0.0, 0.0, 0.0, 0.0],
2-element iterator of Line{Float64, Vector{Float64}}:
 Line([1.0, 0.0, 0.0, 0.0])
 Line([0.0, 1.0, 1.0, 1.0]),
2-element iterator of Ray{Float64, Vector{Float64}}:
 Ray([0.0, 0.0, -1.0, 0.0])
 Ray([0.0, 1.0, 1.0, 0.0])

In [57]:
vrep(f(3))

V-representation CDDLib.CDDGeneratorMatrix{Float64, Float64}:
1-element iterator of Vector{Float64}:
 [0.0, 0.0, 0.0, 0.0],
2-element iterator of Line{Float64, Vector{Float64}}:
 Line([1.0, 0.0, 0.0, 0.0])
 Line([0.0, 1.0, 1.0, 1.0]),
2-element iterator of Ray{Float64, Vector{Float64}}:
 Ray([0.0, -1.0, -0.0, 0.0])
 Ray([0.0, 1.0, 1.0, 0.0])

In [58]:
vrep(f(4))

V-representation CDDLib.CDDGeneratorMatrix{Float64, Float64}:
1-element iterator of Vector{Float64}:
 [0.0, 0.0, 0.0, 0.0],
1-element iterator of Line{Float64, Vector{Float64}}:
 Line([0.0, 1.0, 1.0, 1.0]),
2-element iterator of Ray{Float64, Vector{Float64}}:
 Ray([1.0, 0.0, 0.0, 0.0])
 Ray([0.0, 1.0, 1.0, 0.0])

In [59]:
vrep(f(5))

LoadError: BoundsError: attempt to access 4-element BitVector at index [5]

In [23]:
dim(f(1))

9

In [76]:
using SparseArrays

In [88]:
m = sparse([1,0,0,1])
n = 1

1

In [89]:
a = HyperPlane(m,n)

HyperPlane(sparsevec([1, 4], [1, 1], 4), 1)

In [90]:
m[1] = 0

0

In [92]:
m = 0

0

In [93]:
a

HyperPlane(sparsevec([1, 4], [0, 1], 4), 1)

In [81]:
b = HalfSpace(a.a, a.β)

HalfSpace(sparsevec([1, 4], [1, 1], 4), 1)

In [84]:
b.a[1] =0

0

In [85]:
a

HyperPlane(sparsevec([1, 4], [0, 1], 4), 1)

In [164]:
L = BindingAndCatalysis.L_from_N(N_generator(8,16;min_binder=3,max_binder=5))
length(find_all_vertices(L;asymptotic=true)) == length(asymptotic_perms(compile_regime_catalog(L)))

true

In [ ]:
a. 

In [124]:
a =  compile_regime_catalog(L)

RegimeCatalog{Int64}(8, 16, [[1, 9, 10, 11, 12, 13, 14, 15, 16], [2, 9, 10, 11, 12, 13, 14, 15, 16], [3, 16], [4, 14], [5, 12, 14, 15], [6, 15], [7, 10, 13], [8, 11, 13, 14, 15, 16]], [[1, 0, 0, 0, 0, 0, 0, 0, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 0, 0, 0, 0, 0, 0, 2, 3, 4, 5, 6, 7, 8, 9], [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 3, 4, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 3, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 3, 4, 5, 6]], [[0.0, 0.0, 0.0, 1.0986122886681098, 0.0, 1.6094379124341003, 1.3862943611198906, 1.3862943611198906, 1.9459101490553132], [0.0, 0.6931471805599453, 0.6931471805599453, 0.6931471805599453, 0.0, 1.791759469228055, 0.6931471805599453, 0.6931471805599453, 1.9459101490553132], [0.0, 0.0], [0.0, 0.0], [0.0, 0.6931471805599453, 0.6931471805599453, 0.0], [0.0, 0.0], [0.0, 0.6931471805599453, 1.3862943611198906], [0.0,

In [168]:
@btime find_all_vertices(L;asymptotic=false)

  797.338 ms (16357311 allocations: 422.62 MiB)


56243-element Vector{Vector{Int8}}:
 [1, 2, 3, 4, 5, 6, 7, 8]
 [1, 2, 3, 4, 5, 6, 13, 8]
 [1, 2, 3, 4, 5, 6, 14, 8]
 [1, 2, 3, 4, 5, 6, 15, 8]
 [1, 12, 3, 4, 5, 6, 7, 8]
 [1, 12, 3, 4, 5, 6, 13, 8]
 [1, 12, 3, 4, 5, 6, 14, 8]
 [1, 12, 3, 4, 5, 6, 15, 8]
 [1, 15, 3, 4, 5, 6, 7, 8]
 [1, 15, 3, 4, 5, 6, 13, 8]
 [1, 15, 3, 4, 5, 6, 14, 8]
 [1, 15, 3, 4, 5, 6, 15, 8]
 [1, 16, 3, 4, 5, 6, 7, 8]
 ⋮
 [16, 2, 16, 16, 15, 6, 7, 16]
 [16, 2, 16, 16, 15, 6, 15, 16]
 [16, 16, 16, 16, 15, 6, 7, 16]
 [16, 16, 16, 16, 15, 6, 15, 16]
 [16, 2, 16, 16, 15, 15, 7, 8]
 [16, 2, 16, 16, 15, 15, 15, 8]
 [16, 16, 16, 16, 15, 15, 7, 8]
 [16, 16, 16, 16, 15, 15, 15, 8]
 [16, 2, 16, 16, 15, 15, 7, 16]
 [16, 2, 16, 16, 15, 15, 15, 16]
 [16, 16, 16, 16, 15, 15, 7, 16]
 [16, 16, 16, 16, 15, 15, 15, 16]

In [166]:
@btime nonasymptotic_perms(compile_regime_catalog(L))

  60.386 ms (977905 allocations: 83.61 MiB)


56243-element Vector{Vector{Int64}}:
 [1, 2, 3, 4, 5, 6, 7, 8]
 [1, 2, 3, 4, 5, 6, 13, 8]
 [1, 2, 3, 4, 5, 6, 14, 8]
 [1, 2, 3, 4, 5, 6, 15, 8]
 [1, 12, 3, 4, 5, 6, 7, 8]
 [1, 12, 3, 4, 5, 6, 13, 8]
 [1, 12, 3, 4, 5, 6, 14, 8]
 [1, 12, 3, 4, 5, 6, 15, 8]
 [1, 15, 3, 4, 5, 6, 7, 8]
 [1, 15, 3, 4, 5, 6, 13, 8]
 [1, 15, 3, 4, 5, 6, 14, 8]
 [1, 15, 3, 4, 5, 6, 15, 8]
 [1, 16, 3, 4, 5, 6, 7, 8]
 ⋮
 [16, 2, 16, 16, 15, 6, 7, 16]
 [16, 2, 16, 16, 15, 6, 15, 16]
 [16, 16, 16, 16, 15, 6, 7, 16]
 [16, 16, 16, 16, 15, 6, 15, 16]
 [16, 2, 16, 16, 15, 15, 7, 8]
 [16, 2, 16, 16, 15, 15, 15, 8]
 [16, 16, 16, 16, 15, 15, 7, 8]
 [16, 16, 16, 16, 15, 15, 15, 8]
 [16, 2, 16, 16, 15, 15, 7, 16]
 [16, 2, 16, 16, 15, 15, 15, 16]
 [16, 16, 16, 16, 15, 15, 7, 16]
 [16, 16, 16, 16, 15, 15, 15, 16]

In [179]:
@btime feasible_perms(compile_regime_catalog(L))

  97.066 ms (2105109 allocations: 156.03 MiB)


56243-element Vector{Vector{Int8}}:
 [1, 2, 3, 4, 5, 6, 7, 8]
 [1, 2, 3, 4, 5, 6, 13, 8]
 [1, 2, 3, 4, 5, 6, 14, 8]
 [1, 2, 3, 4, 5, 6, 15, 8]
 [1, 12, 3, 4, 5, 6, 7, 8]
 [1, 12, 3, 4, 5, 6, 13, 8]
 [1, 12, 3, 4, 5, 6, 14, 8]
 [1, 12, 3, 4, 5, 6, 15, 8]
 [1, 15, 3, 4, 5, 6, 7, 8]
 [1, 15, 3, 4, 5, 6, 13, 8]
 [1, 15, 3, 4, 5, 6, 14, 8]
 [1, 15, 3, 4, 5, 6, 15, 8]
 [1, 16, 3, 4, 5, 6, 7, 8]
 ⋮
 [16, 2, 16, 16, 15, 6, 7, 16]
 [16, 2, 16, 16, 15, 6, 15, 16]
 [16, 16, 16, 16, 15, 6, 7, 16]
 [16, 16, 16, 16, 15, 6, 15, 16]
 [16, 2, 16, 16, 15, 15, 7, 8]
 [16, 2, 16, 16, 15, 15, 15, 8]
 [16, 16, 16, 16, 15, 15, 7, 8]
 [16, 16, 16, 16, 15, 15, 15, 8]
 [16, 2, 16, 16, 15, 15, 7, 16]
 [16, 2, 16, 16, 15, 15, 15, 16]
 [16, 16, 16, 16, 15, 15, 7, 16]
 [16, 16, 16, 16, 15, 15, 15, 16]

In [192]:
using SparseArrays, LinearAlgebra
using Base.Threads: nthreads, @threads

function transitiveclosure(L::SparseMatrixCSC{Tv,Ti},Jlen,CJ,mark;countonly=false) where {Tv,Ti<:Integer}
    b = 0
    c = Jlen
    for i=1:Jlen
        mark[CJ[i]] = true
    end
    cp = L.colptr
    rv = L.rowval
    while b<c
        b+=1
        i = CJ[b]
        p = cp[i]
        q = cp[i+1]-1
        for i=p:q
            j = rv[i]
            if !mark[j]
                c+=1
                mark[j]=true
                CJ[c]=j
            end
        end
    end
    for i=1:c
        mark[CJ[i]] = false
    end
    if countonly
        return c
    end
    sort!(view(CJ,1:c))
    return c
end
function solvevec(L::SparseMatrixCSC{Tv,Ti},lowertriangular,x::Vector{Tv},J,CJ,mark) where {Tv,Ti<:Integer}
    @assert size(L,2)==length(x)
    m = length(J)
    for i=1:m
        CJ[i] = J[i]
    end
    c = transitiveclosure(L,m,CJ,mark)
    cp = L.colptr
    rv = L.rowval
    nz = L.nzval
    if lowertriangular
        (a,b,dir) = (1,c,1)
    else
        (a,b,dir) = (c,1,-1)
    end
    for i=a:dir:b
        j = CJ[i]
        p = cp[j]
        q = cp[j+1]-1
        if lowertriangular
            @assert rv[p]==j
            x[j] /= nz[p]
            p+=1
        else
            @assert rv[q]==j
            x[j] /= nz[q]
            q-=1
        end
        alpha = x[j]
        for k=p:q
            x[rv[k]] -= alpha*nz[k]
        end
    end
    return c
end
function solvemat(L::SparseMatrixCSC{Tv,Ti},B::SparseMatrixCSC{Tv,Ti};lowertriangular=true) where {Tv,Ti<:Integer}
    @assert size(L,2)==size(B,1)
    cp = B.colptr
    rv = B.rowval
    nz = B.nzval
    CP = Vector{Ti}(undef,B.n+1)
    CP[1] = 1
    CJ = Vector{Ti}(undef,L.n)
    mark = falses(L.n)
    for i in 1:B.n
        p = cp[i]-1
        q = cp[i+1]-1
        Jlen = q-p
        for j=1:Jlen
            CJ[j]=rv[j+p]
        end
        CP[i+1]=CP[i]+transitiveclosure(L,Jlen,CJ,mark,countonly=true)
    end
    N = CP[end]-1
    RV = Vector{Ti}(undef,N)
    NZ = Vector{Tv}(undef,N)
    x = zeros(Tv,L.n)
    for i = 1:B.n
        p = cp[i]
        q = cp[i+1]-1
        J = view(rv,p:q)
        p -= 1
        for j=1:length(J)
            x[J[j]] = nz[j+p]
        end
        d = solvevec(L,lowertriangular,x,J,CJ,mark)
        c = CP[i]-1
        for j=1:d
            k = CJ[j]
            RV[c+j] = k
            NZ[c+j] = x[k]
            x[CJ[j]] = 0
        end
    end
    SparseMatrixCSC{Tv,Ti}(B.m,B.n,CP,RV,NZ)
end
@enum SolveMode lower=1 upper=2 detect=3
"""
    function solve(L::SparseMatrixCSC{Tv,Ti},B::SparseMatrixCSC{Tv,Ti};solvemode=detect,numthreads=min(B.n,nthreads())) where {Tv,Ti<:Integer}

Solve `L*X=B` for the unknown `X`, where `L` and `B` are sparse matrices. `L` should be either lower or upper triangular. If `numthreads>1` then multithreading is used. `solvemode` should be either `lower`, `upper` or `detect`.
"""
function solve(L::SparseMatrixCSC{Tv,Ti},B::SparseMatrixCSC{Tv,Ti};solvemode=detect,numthreads=min(B.n,nthreads())) where {Tv,Ti<:Integer}
    if solvemode==detect
        if istril(L)
            solvemode=lower
        elseif istriu(L)
            solvemode=upper
        else
            error("`solve` can only be used on lower or upper triangular matrices")
        end
    end
    if numthreads==1
        return solvemat(L,B;lowertriangular=(solvemode==lower))
    end
    dk = B.n/numthreads
    X = Array{SparseMatrixCSC{Tv,Ti}}(undef,numthreads)
    @threads for j=1:numthreads
        a = (j==1) ? 1 : (Int(floor(j*dk)+1))
        b = (j==numthreads) ? B.n : Int(floor((j+1)*dk))
        X[j] = solvemat(L,B[:,a:b];lowertriangular=(solvemode==lower))
    end
    return hcat(X...)
end

struct Factorization{Tv,Ti<:Integer} 
    L::Union{Missing,SparseMatrixCSC{Tv,Ti}}
    U::Union{Missing,SparseMatrixCSC{Tv,Ti}}
    p::Union{Missing,Vector{Ti}}
    q::Union{Missing,Vector{Ti}}
end
"""
    function Factorization(A::SparseMatrixCSC)

Compute a sparse factorization of the sparse matrix `A`. This returns a `Factorization` object `F` with fields `F.L`, `F.U`, `F.p`, `F.q`. The fields `L` and `U` are sparse lower and upper triangular matrices, and `p` and `q` are permutation vectors. Any of these fields can be replaced by the value `missing`.
"""
function Factorization(A::SparseMatrixCSC{Tv,Ti}) where {Tv,Ti<:Integer}
    @assert Tv==Float64 || Tv==ComplexF64
    if size(A,1)==size(A,2)
        if istril(A) return Factorization(A,missing,missing,missing) end
        if istriu(A) return Factorization(missing,A,missing,missing) end
        if ishermitian(A)
            F = cholesky(A;check=false)
            if LinearAlgebra.issuccess(F) return Factorization(sparse(F.L),sparse(sparse(F.L)'),missing,missing) end
            ldlt!(F,A;check=false)
            if LinearAlgebra.issuccess(F)
                LD = sparse(F.LD)
                D = spdiagm(0=>diag(LD))
                L = LD-D+spdiagm(0=>ones(Tv,size(LD,1)))
                U = D*(L')
                return Factorization(L,U,missing,missing)
            end
        end
        F = lu(A)
        R = spdiagm(0=>1 ./F.Rs[F.p])
        p = (F.p==1:length(F.p)) ? missing : F.p
        q = (F.q==1:length(F.q)) ? missing : invperm(F.q)
        return Factorization((R*F.L),(F.U),p,q)
    end
    error("QR decomposition unimplemented")
end

"""
    function Base.:\\(A::Factorization, B::SparseMatrixCSC)

Solve the problem `A*X=B` for the unknown `X`, where `A` is a Factorization object and `B` is sparse.
"""
function Base.:\(A::Factorization{Tv,Ti}, B::SparseMatrixCSC{Tv,Ti}) where {Tv,Ti<:Integer}
    if !ismissing(A.p) B = B[A.p,:]                     end
    if !ismissing(A.L) B = solve(A.L,B;solvemode=lower) end
    if !ismissing(A.U) B = solve(A.U,B;solvemode=upper) end
    if !ismissing(A.q) B = B[A.q,:]                     end
    return B
end
Base.:\(A::Factorization{Tv,Ti}, B::SparseVector{Tv,Ti}) where {Tv,Ti<:Integer} = SparseVector(A\SparseMatrixCSC(B))
Base.:\(A::SparseMatrixCSC{Tv,Ti}, B::SparseMatrixCSC{Tv,Ti}) where {Tv,Ti<:Integer} = Factorization(A)\B
Base.:\(A::SparseMatrixCSC{Tv,Ti}, B::SparseVector{Tv,Ti}) where {Tv,Ti<:Integer} = Factorization(A)\B
Base.transpose(A::Factorization) = Factorization(ismissing(A.U) ? missing : sparse(transpose(A.U)),
                                                 ismissing(A.L) ? missing : sparse(transpose(A.L)),
                                                 ismissing(A.q) ? missing : invperm(A.q),
                                                 ismissing(A.p) ? missing : invperm(A.p))
Base.:/(A::SparseMatrixCSC{Tv,Ti}, B::Factorization{Tv,Ti}) where {Tv,Ti<:Integer} = sparse(transpose(transpose(B)\sparse(transpose(A))))
Base.:/(A::SparseMatrixCSC{Tv,Ti}, B::SparseMatrixCSC{Tv,Ti}) where {Tv,Ti<:Integer} = A/Factorization(B)
Base.inv(A::SparseMatrixCSC{Tv,Ti}) where {Tv,Ti<:Integer} = A\spdiagm(0=>ones(Tv,size(A,1)))

# Rational sparse inverse falls back to exact dense inversion, then sparsifies again.
Base.inv(A::SparseMatrixCSC{Tv,Ti}) where {T<:Integer, Tv<:Rational{T}, Ti<:Integer} = sparse(inv(Matrix(A)))


In [193]:
a = get_M(model,1)

8×8 SparseMatrixCSC{Int64, Int64} with 16 stored entries:
 1  ⋅  ⋅  ⋅   ⋅   ⋅   ⋅   ⋅
 ⋅  1  ⋅  ⋅   ⋅   ⋅   ⋅   ⋅
 ⋅  ⋅  1  ⋅   ⋅   ⋅   ⋅   ⋅
 ⋅  ⋅  ⋅  1   ⋅   ⋅   ⋅   ⋅
 ⋅  1  ⋅  1  -1   ⋅   ⋅   ⋅
 1  1  ⋅  ⋅   ⋅  -1   ⋅   ⋅
 1  1  ⋅  ⋅   ⋅   ⋅  -1   ⋅
 ⋅  ⋅  1  ⋅   1   ⋅   ⋅  -1

In [194]:
inv(a)

LoadError: AssertionError: Tv == Float64 || Tv == ComplexF64