In [1]:
begin
    using Pkg
    dev_folder = joinpath(@__DIR__, "../Examples")
    Pkg.activate(dev_folder)
end
Threads.nthreads()

  Activating project at `~/Realizibility_index/BindingAndCatalysis.jl/Examples`


24

In [ ]:
using Polyhedra
using SparseArrays
using GLMakie # for plotting, we use Makie backend, could also be GLMakie or WGLMakie...


In [3]:
using Revise
using BindingAndCatalysis # import the package

[ Info: Precompiling BindingAndCatalysis [b532a4b1-2c45-4c12-bcaf-8695372aa40c] (cache misses: include_dependency fsize change (2), wrong dep version loaded (2), incompatible header (4))


In [40]:
N = N_generator(10,20; min_binder=2, max_binder=5)

10×20 Matrix{Int64}:
 0  0  0  2  0  2  0  0  0  0  -1   0   0   0   0   0   0   0   0   0
 0  0  0  0  0  1  1  2  0  1   0  -1   0   0   0   0   0   0   0   0
 0  1  0  1  1  0  0  0  0  0   0   0  -1   0   0   0   0   0   0   0
 0  0  0  0  1  0  1  1  1  0   0   0   1  -1   0   0   0   0   0   0
 2  2  0  0  0  0  0  1  0  0   0   0   0   0  -1   0   0   0   0   0
 0  1  0  0  0  0  0  0  0  0   2   0   0   0   2  -1   0   0   0   0
 0  0  1  0  0  0  1  0  0  0   1   0   0   0   0   0  -1   0   0   0
 1  0  0  0  1  0  0  0  0  0   0   1   0   0   0   0   0  -1   0   0
 0  0  0  0  0  0  0  0  0  1   1   0   0   0   1   0   0   1  -1   0
 0  0  0  0  0  1  1  0  0  0   0   1   0   0   0   0   0   0   0  -1

In [41]:
model = Bnc(N=N)
find_all_regimes!(model)

[ Info: ---------------------Start finding all vertices--------------------
[ Info: Finished, with 603460 vertices found and 194080 asymptotic vertices.
[ Info: 2.Calculating nullity for each vertex...
[ Info: 3.Building Regimes...
[ Info: Finished.


In [42]:
a = Set.(get_regimes(model;singular=false))

46864-element Vector{Set{Int64}}:
 Set([5, 4, 6, 7, 2, 10, 9, 8, 3, 1])
 Set([5, 4, 6, 7, 2, 10, 8, 14, 3, 1])
 Set([5, 4, 6, 7, 2, 10, 9, 8, 17, 1])
 Set([5, 4, 6, 7, 2, 10, 8, 17, 14, 1])
 Set([5, 4, 6, 7, 2, 9, 12, 8, 3, 1])
 Set([5, 4, 6, 7, 2, 12, 8, 14, 3, 1])
 Set([5, 4, 6, 7, 2, 9, 12, 8, 17, 1])
 Set([5, 4, 6, 7, 2, 12, 8, 17, 14, 1])
 Set([5, 4, 6, 7, 2, 18, 9, 8, 3, 1])
 Set([5, 4, 6, 7, 2, 18, 8, 14, 3, 1])
 Set([5, 4, 6, 7, 2, 18, 9, 8, 17, 1])
 Set([5, 4, 6, 7, 2, 18, 8, 17, 14, 1])
 Set([5, 4, 6, 7, 2, 9, 8, 3, 1, 19])
 ⋮
 Set([15, 20, 7, 10, 18, 9, 14, 3, 1, 19])
 Set([15, 20, 7, 10, 18, 9, 14, 17, 1, 19])
 Set([5, 16, 20, 7, 10, 18, 9, 3, 1, 19])
 Set([5, 16, 20, 7, 10, 18, 14, 3, 1, 19])
 Set([5, 16, 20, 7, 10, 18, 9, 17, 1, 19])
 Set([5, 16, 20, 7, 10, 18, 14, 17, 1, 19])
 Set([13, 16, 20, 7, 10, 18, 9, 3, 1, 19])
 Set([13, 16, 20, 7, 10, 18, 14, 3, 1, 19])
 Set([13, 16, 20, 7, 10, 18, 9, 17, 1, 19])
 Set([13, 16, 20, 7, 10, 18, 14, 17, 1, 19])
 Set([16, 20, 7, 10, 1

In [43]:
b = Set(a)

Set{Set{Int64}} with 46864 elements:
  Set([4, 16, 6, 20, 15, 18, 9, 12, 3, 1])
  Set([5, 15, 20, 9, 12, 8, 17, 3, 1, 19])
  Set([16, 6, 11, 10, 18, 12, 14, 17, 3, 19])
  Set([5, 15, 16, 11, 20, 7, 9, 12, 3, 19])
  Set([13, 16, 6, 2, 11, 7, 12, 14, 17, 19])
  Set([4, 15, 16, 13, 6, 18, 9, 10, 17, 3])
  Set([4, 13, 16, 2, 7, 15, 14, 17, 1, 19])
  Set([5, 16, 6, 2, 7, 12, 8, 14, 3, 19])
  Set([4, 13, 7, 2, 20, 9, 14, 17, 3, 19])
  Set([4, 15, 13, 6, 20, 9, 12, 8, 3, 19])
  Set([16, 6, 11, 7, 18, 9, 14, 8, 3, 1])
  Set([5, 13, 4, 20, 10, 9, 12, 17, 3, 1])
  Set([5, 16, 6, 2, 7, 12, 8, 17, 14, 1])
  Set([5, 13, 15, 20, 2, 11, 9, 12, 8, 3])
  Set([5, 4, 16, 2, 11, 18, 14, 3, 1, 19])
  Set([5, 13, 16, 6, 2, 7, 20, 8, 14, 3])
  Set([5, 4, 15, 16, 2, 18, 14, 17, 3, 19])
  Set([5, 4, 15, 6, 10, 18, 9, 12, 17, 3])
  Set([5, 4, 15, 16, 2, 10, 9, 12, 8, 17])
  Set([4, 16, 2, 11, 18, 12, 8, 14, 3, 19])
  Set([5, 13, 6, 20, 11, 9, 8, 17, 3, 19])
  Set([5, 4, 6, 15, 2, 18, 9, 17, 3, 1])
  Set([5, 4, 

In [7]:
find_all_regimes!(model)

[ Info: ---------------------Start finding all vertices--------------------
[ Info: Finished, with 20 vertices found and 20 asymptotic vertices.
[ Info: 2.Calculating nullity for each vertex...
[ Info: 3.Building Regimes...
[ Info: Finished.


In [8]:
a = model.L

3×6 SparseMatrixCSC{Int64, Int64} with 9 stored entries:
 1  ⋅  ⋅  ⋅  1  1
 ⋅  1  ⋅  2  1  1
 ⋅  ⋅  1  ⋅  ⋅  1

In [10]:
f,ax = draw_ROP(model, [(1,2),(1,3),(1,4)],npoints=1000000)

[ Info: Start calculating vertices neighbor graph, It may takes a while.
Progress: 100%|█████████████████████████████████████████| Time: 0:00:00
[ Info: Calculating vertices neighbor graph with qK change dir
Progress: 100%|█████████████████████████████████████████| Time: 0:00:00


(Scene(1 children, 0 plots), Axis3 (71 plots))

In [11]:
display(f)

GLMakie.Screen(...)

In [14]:
f,ax,p = draw_graph(model)

(Scene(1 children, 0 plots), Axis (2 plots), Plot{GraphMakie.graphplot, Tuple{Graphs.SimpleGraphs.SimpleDiGraph{Int64}}})

In [15]:
display(f)

GLMakie.Screen(...)

In [10]:
find_all_vertices!(md)

[ Info: ---------------------Start finding all vertices--------------------
[ Info: Finished, with 5 vertices found and 4 asymptotic vertices.
[ Info: -------------Start calculating nullity for each vertex, it also takes a while.------------
[ Info: 1.Building Nρ_inv cache in parallel...
Progress: 100%|█████████████████████████████████████████| Time: 0:00:00
[ Info: 2.Calculating nullity for each vertex in parallel...
Progress: 100%|█████████████████████████████████████████| Time: 0:00:00


5-element Vector{Vector{Int8}}:
 [1, 2]
 [1, 3]
 [2, 2]
 [3, 2]
 [3, 3]

In [36]:
get_perm(model,17)

3-element Vector{Int64}:
 6
 2
 5

In [35]:
get_nullities(model)

24-element Vector{Int64}:
 0
 0
 0
 0
 0
 1
 0
 0
 0
 0
 0
 1
 0
 0
 1
 1
 1
 1
 0
 1
 1
 1
 1
 2

In [14]:
get_C_x(md,[1,2])

3×3 SparseMatrixCSC{Int64, Int64} with 6 stored entries:
 1  -1   ⋅
 1   ⋅  -1
 ⋅   1  -1

In [59]:
a = _build_matrix_helper(L)

Matrix_helper{Int64}(3, [[1, 2, 3], [2, 3]], [[1, 2, 3], [0, 1, 2]], [[0.0, 0.0, 0.0], [0.3010299956639812, 0.0]], [1, 3, 4], 3, Vector{Vector{ChoiceIneq}}[[[ChoiceIneq(1, 1, 2, 0.0), ChoiceIneq(2, 1, 3, 0.0)], [ChoiceIneq(1, -1, 1, 0.0), ChoiceIneq(3, 1, 3, 0.0)], [ChoiceIneq(2, -1, 1, 0.0), ChoiceIneq(3, -1, 2, 0.0)]], [[ChoiceIneq(4, 1, 3, 0.3010299956639812)], [ChoiceIneq(4, -1, 2, -0.3010299956639812)]]], Hyperplane_perm{Int64}[Hyperplane_perm{Int64}(1, 2, 1, 1, 0.0, sparsevec([1, 2], Int8[1, -1], 3), sparsevec([1, 2], Int8[-1, 1], 3)), Hyperplane_perm{Int64}(1, 3, 1, 1, 0.0, sparsevec([1, 3], Int8[1, -1], 3), sparsevec([1, 3], Int8[-1, 1], 3)), Hyperplane_perm{Int64}(2, 3, 1, 1, 0.0, sparsevec([2, 3], Int8[1, -1], 3), sparsevec([2, 3], Int8[-1, 1], 3)), Hyperplane_perm{Int64}(2, 3, 2, 1, 0.3010299956639812, sparsevec([2, 3], Int8[1, -1], 3), sparsevec([2, 3], Int8[-1, 1], 3))])

In [60]:
b = _enumerate_asymptotic_regimes(a)

4-element Vector{Vector{Int64}}:
 [1, 2]
 [1, 3]
 [2, 2]
 [3, 3]

In [61]:
_enumerate_all_regimes(a)[1]

5-element Vector{Vector{Int64}}:
 [1, 2]
 [1, 3]
 [2, 2]
 [3, 2]
 [3, 3]

In [62]:
P,P0 = _calc_P_P0(b[1], a)

(sparse([1, 2], [1, 2], Int8[1, 1], 2, 3), [0.0, 0.3010299956639812])

In [68]:
C,C0 = _calc_C_C0(b[1], a)

(sparse([1, 2, 1, 3, 2, 3], [1, 1, 2, 2, 3, 3], Int8[1, 1, -1, 1, -1, -1], 3, 3), [0.0, 0.0, 0.3010299956639812])

In [69]:
C

3×3 SparseMatrixCSC{Int8, Int64} with 6 stored entries:
 1  -1   ⋅
 1   ⋅  -1
 ⋅   1  -1

In [65]:
get_C0_x(md, b[1])

3-element Vector{Float64}:
 0.0
 0.0
 0.3010299956639812

In [66]:
get_C_x(md, b[1])

3×3 SparseMatrixCSC{Int64, Int64} with 6 stored entries:
 1  -1   ⋅
 1   ⋅  -1
 ⋅   1  -1

In [30]:
a.choice_logcoeff

2-element Vector{Vector{Float64}}:
 [0.0, 0.0]
 [0.0, 0.0]

In [15]:
struct A
    a::Vector{Int}
end

In [16]:
struct B
    a::A
    b::Int8
end

In [17]:
u = A([1,4,3,5,6])

A([1, 4, 3, 5, 6])

In [18]:
x = B(u, 3)
y = B(u,9)

B(A([1, 4, 3, 5, 6]), 9)

In [20]:
x.a.a[1] = 100

100

In [21]:
x.a.a

5-element Vector{Int64}:
 100
   4
   3
   5
   6

In [22]:
y.a.a

5-element Vector{Int64}:
 100
   4
   3
   5
   6

In [34]:
_perm_process([1,3], a)

([0.0, 0.0], Tuple{Int64, Int8}[(1, 1), (2, -1)], 0)

In [64]:
model = let
    N = N_generator(4,8)
    Bnc(N=N)
end


----------Binding Network Summary:-------------
Number of species (n): 8
Number of conserved quantities (d): 4
Number of reactions (r): 4
L matrix: [1 0 … 1 0; 0 1 … 1 1; 0 0 … 0 1; 0 0 … 0 1]
N matrix: [0 1 … 0 0; 1 1 … 0 0; 1 1 … -1 0; 0 0 … 0 -1]
Direction of binding reactions: forward
Catalysis involved: No
Regimes constructed: No
-----------------------------------------------

In [66]:
model.L

4×8 Matrix{Int64}:
 1  0  0  0  0  1  1  0
 0  1  0  0  1  1  1  1
 0  0  1  0  0  0  0  1
 0  0  0  1  1  0  0  1

In [67]:
f(i)= let
    C,C0,nulliy = get_C_C0_nullity(model,i)
    get_polyhedron(hcat(C0,C), zeros(size(C0)), nulliy)
end

f (generic function with 1 method)

In [68]:
g(i) = let
    C,C0 = get_C_C0_x(model,i)
    get_polyhedron(hcat(C0,C), zeros(size(C0)))
end

g (generic function with 1 method)

In [69]:
vrep(g(1))

[ Info: ---------------------Start finding all vertices--------------------
[ Info: Finished, with 66 vertices found and 66 asymptotic vertices.
[ Info: -------------Start calculating nullity for each vertex, it also takes a while.------------
[ Info: 1.Building Nρ_inv cache in parallel...
[ Info: 2.Calculating nullity for each vertex in parallel...


V-representation CDDLib.CDDGeneratorMatrix{Float64, Float64}:
1-element iterator of Vector{Float64}:
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
2-element iterator of Line{Float64, Vector{Float64}}:
 Line([1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
 Line([0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]),
9-element iterator of Ray{Float64, Vector{Float64}}:
 Ray([0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -1.0, 0.0])
 Ray([0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
 Ray([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0])
 Ray([0.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1.0, -1.0, 0.0])
 Ray([0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0])
 Ray([0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0])
 Ray([0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0])
 Ray([0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0])
 Ray([0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0])

In [70]:
vrep(g(2))

V-representation CDDLib.CDDGeneratorMatrix{Float64, Float64}:
1-element iterator of Vector{Float64}:
 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
2-element iterator of Line{Float64, Vector{Float64}}:
 Line([1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
 Line([0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]),
9-element iterator of Ray{Float64, Vector{Float64}}:
 Ray([0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -0.0, -1.0, 0.0])
 Ray([0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
 Ray([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0])
 Ray([0.0, -1.0, 0.0, 0.0, 0.0, 0.0, -1.0, -1.0, 0.0])
 Ray([0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0])
 Ray([0.0, 1.0, 1.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0])
 Ray([0.0, 0.0, 0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0])
 Ray([0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0])
 Ray([0.0, 0.0, 0.0, -1.0, 0.0, 0.0, 0.0, 0.0, 0.0])

In [55]:
vrep(f(1))

[ Info: ---------------------Start finding all vertices--------------------
[ Info: Finished, with 4 vertices found and 4 asymptotic vertices.
[ Info: -------------Start calculating nullity for each vertex, it also takes a while.------------
[ Info: 1.Building Nρ_inv cache in parallel...
[ Info: 2.Calculating nullity for each vertex in parallel...


V-representation CDDLib.CDDGeneratorMatrix{Float64, Float64}:
1-element iterator of Vector{Float64}:
 [0.0, 0.0, 0.0, 0.0],
2-element iterator of Line{Float64, Vector{Float64}}:
 Line([1.0, 0.0, 0.0, 0.0])
 Line([0.0, 1.0, 1.0, 1.0]),
2-element iterator of Ray{Float64, Vector{Float64}}:
 Ray([0.0, -1.0, 0.0, 0.0])
 Ray([0.0, -0.0, -1.0, 0.0])

In [56]:
vrep(f(2))

V-representation CDDLib.CDDGeneratorMatrix{Float64, Float64}:
1-element iterator of Vector{Float64}:
 [0.0, 0.0, 0.0, 0.0],
2-element iterator of Line{Float64, Vector{Float64}}:
 Line([1.0, 0.0, 0.0, 0.0])
 Line([0.0, 1.0, 1.0, 1.0]),
2-element iterator of Ray{Float64, Vector{Float64}}:
 Ray([0.0, 0.0, -1.0, 0.0])
 Ray([0.0, 1.0, 1.0, 0.0])

In [57]:
vrep(f(3))

V-representation CDDLib.CDDGeneratorMatrix{Float64, Float64}:
1-element iterator of Vector{Float64}:
 [0.0, 0.0, 0.0, 0.0],
2-element iterator of Line{Float64, Vector{Float64}}:
 Line([1.0, 0.0, 0.0, 0.0])
 Line([0.0, 1.0, 1.0, 1.0]),
2-element iterator of Ray{Float64, Vector{Float64}}:
 Ray([0.0, -1.0, -0.0, 0.0])
 Ray([0.0, 1.0, 1.0, 0.0])

In [58]:
vrep(f(4))

V-representation CDDLib.CDDGeneratorMatrix{Float64, Float64}:
1-element iterator of Vector{Float64}:
 [0.0, 0.0, 0.0, 0.0],
1-element iterator of Line{Float64, Vector{Float64}}:
 Line([0.0, 1.0, 1.0, 1.0]),
2-element iterator of Ray{Float64, Vector{Float64}}:
 Ray([1.0, 0.0, 0.0, 0.0])
 Ray([0.0, 1.0, 1.0, 0.0])

In [59]:
vrep(f(5))

LoadError: BoundsError: attempt to access 4-element BitVector at index [5]

In [23]:
dim(f(1))

9

In [76]:
using SparseArrays

In [88]:
m = sparse([1,0,0,1])
n = 1

1

In [89]:
a = HyperPlane(m,n)

HyperPlane(sparsevec([1, 4], [1, 1], 4), 1)

In [90]:
m[1] = 0

0

In [92]:
m = 0

0

In [93]:
a

HyperPlane(sparsevec([1, 4], [0, 1], 4), 1)

In [81]:
b = HalfSpace(a.a, a.β)

HalfSpace(sparsevec([1, 4], [1, 1], 4), 1)

In [84]:
b.a[1] =0

0

In [85]:
a

HyperPlane(sparsevec([1, 4], [0, 1], 4), 1)

In [164]:
L = BindingAndCatalysis.L_from_N(N_generator(8,16;min_binder=3,max_binder=5))
length(find_all_vertices(L;asymptotic=true)) == length(asymptotic_perms(compile_regime_catalog(L)))

true

In [ ]:
a. 

In [124]:
a =  compile_regime_catalog(L)

RegimeCatalog{Int64}(8, 16, [[1, 9, 10, 11, 12, 13, 14, 15, 16], [2, 9, 10, 11, 12, 13, 14, 15, 16], [3, 16], [4, 14], [5, 12, 14, 15], [6, 15], [7, 10, 13], [8, 11, 13, 14, 15, 16]], [[1, 0, 0, 0, 0, 0, 0, 0, 2, 3, 4, 5, 6, 7, 8, 9], [0, 1, 0, 0, 0, 0, 0, 0, 2, 3, 4, 5, 6, 7, 8, 9], [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2], [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 2, 0, 3, 4, 0], [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0], [0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0, 3, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 2, 0, 3, 4, 5, 6]], [[0.0, 0.0, 0.0, 1.0986122886681098, 0.0, 1.6094379124341003, 1.3862943611198906, 1.3862943611198906, 1.9459101490553132], [0.0, 0.6931471805599453, 0.6931471805599453, 0.6931471805599453, 0.0, 1.791759469228055, 0.6931471805599453, 0.6931471805599453, 1.9459101490553132], [0.0, 0.0], [0.0, 0.0], [0.0, 0.6931471805599453, 0.6931471805599453, 0.0], [0.0, 0.0], [0.0, 0.6931471805599453, 1.3862943611198906], [0.0,

In [168]:
@btime find_all_vertices(L;asymptotic=false)

  797.338 ms (16357311 allocations: 422.62 MiB)


56243-element Vector{Vector{Int8}}:
 [1, 2, 3, 4, 5, 6, 7, 8]
 [1, 2, 3, 4, 5, 6, 13, 8]
 [1, 2, 3, 4, 5, 6, 14, 8]
 [1, 2, 3, 4, 5, 6, 15, 8]
 [1, 12, 3, 4, 5, 6, 7, 8]
 [1, 12, 3, 4, 5, 6, 13, 8]
 [1, 12, 3, 4, 5, 6, 14, 8]
 [1, 12, 3, 4, 5, 6, 15, 8]
 [1, 15, 3, 4, 5, 6, 7, 8]
 [1, 15, 3, 4, 5, 6, 13, 8]
 [1, 15, 3, 4, 5, 6, 14, 8]
 [1, 15, 3, 4, 5, 6, 15, 8]
 [1, 16, 3, 4, 5, 6, 7, 8]
 ⋮
 [16, 2, 16, 16, 15, 6, 7, 16]
 [16, 2, 16, 16, 15, 6, 15, 16]
 [16, 16, 16, 16, 15, 6, 7, 16]
 [16, 16, 16, 16, 15, 6, 15, 16]
 [16, 2, 16, 16, 15, 15, 7, 8]
 [16, 2, 16, 16, 15, 15, 15, 8]
 [16, 16, 16, 16, 15, 15, 7, 8]
 [16, 16, 16, 16, 15, 15, 15, 8]
 [16, 2, 16, 16, 15, 15, 7, 16]
 [16, 2, 16, 16, 15, 15, 15, 16]
 [16, 16, 16, 16, 15, 15, 7, 16]
 [16, 16, 16, 16, 15, 15, 15, 16]

In [166]:
@btime nonasymptotic_perms(compile_regime_catalog(L))

  60.386 ms (977905 allocations: 83.61 MiB)


56243-element Vector{Vector{Int64}}:
 [1, 2, 3, 4, 5, 6, 7, 8]
 [1, 2, 3, 4, 5, 6, 13, 8]
 [1, 2, 3, 4, 5, 6, 14, 8]
 [1, 2, 3, 4, 5, 6, 15, 8]
 [1, 12, 3, 4, 5, 6, 7, 8]
 [1, 12, 3, 4, 5, 6, 13, 8]
 [1, 12, 3, 4, 5, 6, 14, 8]
 [1, 12, 3, 4, 5, 6, 15, 8]
 [1, 15, 3, 4, 5, 6, 7, 8]
 [1, 15, 3, 4, 5, 6, 13, 8]
 [1, 15, 3, 4, 5, 6, 14, 8]
 [1, 15, 3, 4, 5, 6, 15, 8]
 [1, 16, 3, 4, 5, 6, 7, 8]
 ⋮
 [16, 2, 16, 16, 15, 6, 7, 16]
 [16, 2, 16, 16, 15, 6, 15, 16]
 [16, 16, 16, 16, 15, 6, 7, 16]
 [16, 16, 16, 16, 15, 6, 15, 16]
 [16, 2, 16, 16, 15, 15, 7, 8]
 [16, 2, 16, 16, 15, 15, 15, 8]
 [16, 16, 16, 16, 15, 15, 7, 8]
 [16, 16, 16, 16, 15, 15, 15, 8]
 [16, 2, 16, 16, 15, 15, 7, 16]
 [16, 2, 16, 16, 15, 15, 15, 16]
 [16, 16, 16, 16, 15, 15, 7, 16]
 [16, 16, 16, 16, 15, 15, 15, 16]

In [179]:
@btime feasible_perms(compile_regime_catalog(L))

  97.066 ms (2105109 allocations: 156.03 MiB)


56243-element Vector{Vector{Int8}}:
 [1, 2, 3, 4, 5, 6, 7, 8]
 [1, 2, 3, 4, 5, 6, 13, 8]
 [1, 2, 3, 4, 5, 6, 14, 8]
 [1, 2, 3, 4, 5, 6, 15, 8]
 [1, 12, 3, 4, 5, 6, 7, 8]
 [1, 12, 3, 4, 5, 6, 13, 8]
 [1, 12, 3, 4, 5, 6, 14, 8]
 [1, 12, 3, 4, 5, 6, 15, 8]
 [1, 15, 3, 4, 5, 6, 7, 8]
 [1, 15, 3, 4, 5, 6, 13, 8]
 [1, 15, 3, 4, 5, 6, 14, 8]
 [1, 15, 3, 4, 5, 6, 15, 8]
 [1, 16, 3, 4, 5, 6, 7, 8]
 ⋮
 [16, 2, 16, 16, 15, 6, 7, 16]
 [16, 2, 16, 16, 15, 6, 15, 16]
 [16, 16, 16, 16, 15, 6, 7, 16]
 [16, 16, 16, 16, 15, 6, 15, 16]
 [16, 2, 16, 16, 15, 15, 7, 8]
 [16, 2, 16, 16, 15, 15, 15, 8]
 [16, 16, 16, 16, 15, 15, 7, 8]
 [16, 16, 16, 16, 15, 15, 15, 8]
 [16, 2, 16, 16, 15, 15, 7, 16]
 [16, 2, 16, 16, 15, 15, 15, 16]
 [16, 16, 16, 16, 15, 15, 7, 16]
 [16, 16, 16, 16, 15, 15, 15, 16]

In [193]:
a = get_M(model,1)

8×8 SparseMatrixCSC{Int64, Int64} with 16 stored entries:
 1  ⋅  ⋅  ⋅   ⋅   ⋅   ⋅   ⋅
 ⋅  1  ⋅  ⋅   ⋅   ⋅   ⋅   ⋅
 ⋅  ⋅  1  ⋅   ⋅   ⋅   ⋅   ⋅
 ⋅  ⋅  ⋅  1   ⋅   ⋅   ⋅   ⋅
 ⋅  1  ⋅  1  -1   ⋅   ⋅   ⋅
 1  1  ⋅  ⋅   ⋅  -1   ⋅   ⋅
 1  1  ⋅  ⋅   ⋅   ⋅  -1   ⋅
 ⋅  ⋅  1  ⋅   1   ⋅   ⋅  -1

In [194]:
inv(a)

LoadError: AssertionError: Tv == Float64 || Tv == ComplexF64